version: '3.5'

services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'generic_tables'
      MYSQL_ROOT_PASSWORD: 's3cr3t'
      TZ: 'America/Sao_Paulo'
    ports:
      - "3306:3306"