INSERT INTO USER (ID, USERNAME, EMAIL, PASSWORD, STATUS) VALUES (1, 'user1', 'user1@email.com', '$2a$11$cczmwDopIyMkDU9fa.XYAOmcDQ1kMMl1q07OHSFdI5UQXh7YhxgUS', true);
INSERT INTO USER (ID, USERNAME, EMAIL, PASSWORD, STATUS) VALUES (2, 'user2', 'user2@email.com', '$2a$11$wzdLMfsMqfkzBABvAMN5KOACXIAJP3lAJgltLgENhqJuqYF3y7z4i', true);
INSERT INTO USER (ID, USERNAME, EMAIL, PASSWORD, STATUS) VALUES (3, 'user3', 'user3@email.com', '$2a$11$kUFtvRQEZkBjWVEbPaCcKexaIUWwTkB0yjaxpVm2zpWJ4sGIsmOJu', true);
INSERT INTO USER (ID, USERNAME, EMAIL, PASSWORD, STATUS) VALUES (4, 'user4', 'user4@email.com', '$2a$11$ce4nuG9nFH4VVsdsBfWef.NAefKJtvnq8HvbOtWadypv00BnIUuc2', true);

INSERT INTO USER_ROLE (ID, USER_ID, ROLE_NAME) VALUES (1, 1, 'ADMIN');
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_NAME) VALUES (5, 1, 'SUPPORT');
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_NAME) VALUES (2, 2, 'ADMIN');
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_NAME) VALUES (3, 3, 'USER');
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_NAME) VALUES (4, 4, 'USER');